spring.application.name=ApiREalSteel
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.springframework.web=WARN
logging.level.com.api.realsteel=DEBUG
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Brevo API HTTP — no usa SMTP
brevo.api.key=${BREVO_API_KEY:}