spring.application.name=RealSteel

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.arprxyfctwqnvwknzimb&password=cacavacapolaca&sslmode=require
spring.datasource.username=postgres.arprxyfctwqnvwknzimb
spring.datasource.password=cacavacapolaca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG